### ISSUE TITLE
ios工程出错

### ISSUE THREAD

**Issue by deekea** [fluttercandies/flutter_image_editor#10]
..../flutter/.pub-cache/hosted/pub.flutter-io.cn/image_editor-0.1.4/ios/Classes/FlutterImageEditorPlugin.m:2:9: 'image_editor/image_editor-Swift.h' file not found

请问这个问题怎么解决？

**Comment by CaiJingLong** [comment]
1. Try to update pod version. My version is `1.8.4`.
2. Run next command in console:

```bash
flutter pub get
cd ios
pod install
```

3. Edit your `Podfile` file.

```rb
# Insert next line.
use_frameworks! 
target 'Runner' do

...
```

**Comment by CaiJingLong** [comment]
Oc calls the swift plugin issue.
There is also have a method simple to resolved it, if your ios part of the code has not been modified, delete your ios folder, and recreate use command `$ flutter create .`

**Comment by deekea** [comment]
thanks. it work just add use_frameworks! into Podfile file. Then pod install and build.
