### ISSUE TITLE
Support platform interface 

### ISSUE THREAD

**Issue by CaiJingLong** [fluttercandies/flutter_image_editor#101]
**For other Pull Requests, please wait for the platform interface to complete**

Since developers have different development languages, in order to support more target platforms, we are prepared to use platform interfaces to provide standard interfaces, so that other desktop platforms and the web can also be supported.

- https://docs.flutter.dev/development/packages-and-plugins/developing-packages#federated-plugins

**Comment by CaiJingLong** [comment]
There is a problem:

Because the `ImageEditor` interface signature uses the `File` of `dart:io`.
Therefore, we cannot be used without breaking change to support web. 
So, web need wait 2.0 version.

**Comment by AlexV525** [comment]
It's a common situation to support platform interface by a breaking change.
