### ISSUE TITLE
[Bug report] Example links is broken

### ISSUE THREAD

**Issue by flaviolacer** [fluttercandies/flutter_image_editor#109]
### Version

latest

### Platforms

dart

### Device Model

Any Device

### flutter info

```sh
Hi. The links for the examples is broken and thre isn´t working code.
Ex:
https://github.com/fluttercandies/flutter_image_editor/blob/main/example/lib/main.dart
```

### How to reproduce?

https://pub.dev/packages/image_editor/example

just click on example link.

**Comment by CaiJingLong** [comment]
Need more info, I can't reproduct

**Comment by CaiJingLong** [comment]
Update README in https://github.com/fluttercandies/flutter_image_editor/commit/50f2571d77a1f4f4be71d621890afc6e4b9ca27c, thanks for report.
