### ISSUE TITLE
[Bug report] file example is not find

### ISSUE THREAD

**Issue by MakKit113** [fluttercandies/flutter_image_editor#113]
### Version

All

### Platforms

dart

### Device Model

All

### flutter info

```sh
README prodive example link is all fail
```

### How to reproduce?

Click this :
https://github.com/fluttercandies/flutter_image_editor/blob/main/example/lib/draw_example_page.dart

**Comment by CaiJingLong** [comment]
Update README in https://github.com/fluttercandies/flutter_image_editor/commit/50f2571d77a1f4f4be71d621890afc6e4b9ca27c, thanks for report.
