### ISSUE TITLE
[Feature request] Support Android 15

### ISSUE THREAD

**Issue by Tom3652** [fluttercandies/flutter_image_editor#140]
### Platforms

Android

### Description

When i build using targetSdkVersion 35 or compileSdkVersion 35 to support android 15, i have the following error : 

```
e: file:///Users/foxtom/.pub-cache/hosted/pub.dev/image_editor_common-1.1.2/android/src/main/kotlin/com/fluttercandies/image_editor/core/HandleExtension.kt:10:56 Argument type mismatch: actual type is 'android.graphics.Bitmap.Config?', but 'android.graphics.Bitmap.Config' was expected.
```

### Why

It would be nice to already start now supporting the latest android APIs, for android 15 especially.

**Comment by CaiJingLong** [comment]
Try to use `image_editor: 1.6.0`

**Comment by Tom3652** [comment]
Thank you this is working fine !
