### ISSUE TITLE
MissingPluginException (memoryToMemory) on ImageEditor.editImage

### ISSUE THREAD

**Issue by srcmkr** [fluttercandies/flutter_image_editor#20]
Hey there,

I've taken your example (advanced_page.dart), but when flutter executes
`ImageEditor.editImage(
      image: img,
      imageEditorOption: option,
    ).then((result) {
      print(result);
    }).catchError((error) => print(error));`
following error will be thrown:
`flutter: MissingPluginException(No implementation found for method memoryToMemory on channel top.kikt/flutter_image_editor)`

What am I missing?

**Comment by srcmkr** [comment]
`flutter clean` fixed it for me (Ref: https://github.com/flutter/flutter/issues/10912#issuecomment-357932578)
Keeping this issue for others to find.

**Comment by CaiJingLong** [comment]
What helps you is not flutter clean.
This plugin introduces native functions.You must exit the application completely and restart it. You just restarted the application after flutter clean.
