### ISSUE TITLE
is there a way to rotate by angle?

### ISSUE THREAD

**Issue by fenchai23** [fluttercandies/flutter_image_editor#23]
I would like to add a slider to rotate:

this is how far I got:

```Dart
Expanded(
  child: Slider(
    divisions: 361,
    value: _rotation,
    min: -180,
    max: 180,
    label: '$_rotation°',
    onChanged: (n) {
      setState(() {
        _rotation = n.roundToDouble();
        editorKey.currentState.editAction.rotate(
            _rotation,
            editorKey.currentState.getCropRect(),
            BoxFit.fitHeight);
      });
    },
  ),
),
```

It rotates into oblivion 😅

**Comment by CaiJingLong** [comment]
I don't know your mean.

**Comment by CaiJingLong** [comment]
This plugin only deals with data, angle rotation supports int value (Degree, 0~359).

**Comment by fenchai23** [comment]
@CaiJingLong ok so I changed min to 0 and max to 359 but it's still giving me BoxContrains has a negative minimum width

`The following assertion was thrown building Container(constraints: BoxConstraints(w=-9.5, h=40.0; NOT NORMALIZED), dirty):`

could you provide an example for a slider? thank you

**Comment by CaiJingLong** [comment]
https://github.com/fluttercandies/flutter_image_editor/blob/461fe8eef0a8bc8b364ab03c4a79347c5ec8e2a0/example/lib/home_page.dart#L103-L105

The example of plugin have use of `RotateOption`.

This project only deals with data, and the UI display is not within the scope of this library.

**Comment by fenchai23** [comment]
I see, so it's still not possible to display the rotation yet. understood. thanks

**Comment by CaiJingLong** [comment]
How to display rotate Image of flutter and show, I think you should consult the flutter team or developer of your Image library.

**Comment by CaiJingLong** [comment]
If you use extended_image , I think you need post issue to [extended_image](https://github.com/fluttercandies/extended_image/issues), not here.

**Comment by fenchai23** [comment]
oops, sorry, because the the package edited the images so I thought it could rotate the image as well.
