### ISSUE TITLE
Platform exception

### ISSUE THREAD

**Issue by visual-velocity** [fluttercandies/flutter_image_editor#24]
log:

<details>
PlatformException(decode bitmap error, null, null)

E/flutter ( 2985): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(decode bitmap error, null, null)
E/flutter ( 2985): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 2985): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 2985): <asynchronous suspension>
E/flutter ( 2985): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 2985): #3      NativeChannel.memoryToMemory (package:image_editor/src/channel.dart:37:21)
E/flutter ( 2985): #4      ImageHandler.handleAndGetUint8List (package:image_editor/src/image_handler.dart:48:30)
E/flutter ( 2985): #5      ImageEditor.editImage (package:image_editor/image_editor.dart:32:27)
E/flutter ( 2985): #6      _ImageEditWidgetState.crop (package:gintaa_people/widgets/image_edit/image_edit.dart:317:40)
E/flutter ( 2985): #7      _ImageEditWidgetState.build.<anonymous closure> (package:gintaa_people/widgets/image_edit/image_edit.dart:114:17)
E/flutter ( 2985): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter ( 2985): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter ( 2985): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 2985): #11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter ( 2985): #12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter ( 2985): #13     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter ( 2985): #14     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 2985): #15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 2985): #16     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 2985): #17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 2985): #18     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 2985): #19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 2985): #20     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 2985): #21     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 2985): #22     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 2985): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 2985): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 2985): #25     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter ( 2985): #26     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 2985): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 2985): #28     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter ( 2985): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)

</details>
Note - JDK 1.14, Gradle 6.4.1 and Flutter 1.17.2

**Comment by CaiJingLong** [comment]
This situation should be a problem with your picture format.
If you need further assistance, please make a complete reproducible code repository, and also include pictures of your errors.

**Comment by visual-velocity** [comment]
Last day it's working fine but today i got this issue.I
used ExtendedNetworkImageProvider inside
ExtendedImageGesturePageView.builder.
I am getting this issue inside this code block.

final state = editorKey[currentIndex].currentState;

final rect = state.getCropRect();
final action = state.editAction;
final radian = action.rotateAngle;

final flipHorizontal = action.flipY;
final flipVertical = action.flipX;
// final img = await getImageFromEditorKey(editorKey);
final img = state.rawImageData;

ImageEditorOption option = ImageEditorOption();

option.addOption(ClipOption.fromRect(rect));
option.addOption(FlipOption(horizontal: flipHorizontal, vertical:
flipVertical));
if (action.hasRotateAngle) {
 option.addOption(RotateOption(radian.toInt()));
 }
option.outputFormat = OutputFormat.png(90);
final start = DateTime.now();
final result = await ImageEditor.editImage(
 image: img,
 imageEditorOption: option,
 );

**Comment by visual-velocity** [comment]
listOfSelectedImage = [
      new SelectedImage(originalFilePath: "
https://picsum.photos/id/59/2000/3000", key: new
GlobalKey<ExtendedImageEditorState>(), isSelected: false,localKey:
ValueKey('__Key0__'),),
      new SelectedImage(originalFilePath: "
https://picsum.photos/id/459/800/600", key: new
GlobalKey<ExtendedImageEditorState>(), isSelected: false,localKey:
ValueKey('__Key1__'),),
      new SelectedImage(originalFilePath: "
https://picsum.photos/id/599/800/600", key: new
GlobalKey<ExtendedImageEditorState>(), isSelected: false,localKey:
ValueKey('__Key2__'),),
      new SelectedImage(originalFilePath: "
https://picsum.photos/id/621/800/600", key: new
GlobalKey<ExtendedImageEditorState>(), isSelected: false,localKey:
ValueKey('__Key3__'),),
      new SelectedImage(originalFilePath: "
https://picsum.photos/id/730/800/600", key: new
GlobalKey<ExtendedImageEditorState>(), isSelected: false,localKey:
ValueKey('__Key4__'),),
      new SelectedImage(originalFilePath: "
https://picsum.photos/id/171/800/600", key: new
GlobalKey<ExtendedImageEditorState>(), isSelected: false,localKey:
ValueKey('__Key5__'),),
      new SelectedImage(originalFilePath: "
https://picsum.photos/id/292/800/600", key: new
GlobalKey<ExtendedImageEditorState>(), isSelected: false,localKey:
ValueKey('__Key6__'),),
      new SelectedImage(originalFilePath: "
https://picsum.photos/id/883/800/600", key: new
GlobalKey<ExtendedImageEditorState>(), isSelected: false,localKey:
ValueKey('__Key7__'),),
    ];

**Comment by CaiJingLong** [comment]
Your code doesn't even have basic code highlighting and formatting. I can't understand it, sorry.

If possible, please provide a working code repository, or a project zip file, or dart single file / code snippet without any private file dependencies

**Comment by visual-velocity** [comment]
Actually i'm not able to share my code due to my organization policy only i
share the sample of code.
here i'm getting errors .
final result = await ImageEditor.editImage(
 image: img,
 imageEditorOption: option,
 );
When the sample image has 2000 x 3000 resolution then the issue is
generating most of the time.
When the sample image has 800 x 900 or less than its resolution then the
issue is generating some of the time.

**Comment by visual-velocity** [comment]
I want to get or capture 500 x 500 size of image after cropping then how it
can be possible.

**Comment by CaiJingLong** [comment]
Can't understand your question.
In addition, you don't have to share your complete working code, but use flutter create to create a new project and use a minimal reproducible code to reproduce the effect or bug you want.
If you ca n’t provide, I ca n’t help you,

In addition, you can run the example source code provided by this project and understand how the code works
