### ISSUE TITLE
(OS Error: Permission denied, errno = 13).

### ISSUE THREAD

**Issue by visual-velocity** [fluttercandies/flutter_image_editor#39]
I cannot upload/load image from gallery and external storage. This is my logcat
FileSystemException: Cannot open file, path = '/storage/emulated/0/DCIM/s9camera/Pic_2020_06_04_19_36_15.jpg' (OS Error: Permission denied, errno = 13).
Android - 29
I'm using permission_handler package for handle permission. Storage and Access Media Location permission has already granted by user but the issue is generated every time when pick image or video from external storage. Inside manifest file we have added android:requestLegacyExternalStorage="true"
Suddenly i get issue on the production app , please support us

**Comment by CaiJingLong** [comment]
The code of this library only processes data, and has nothing to do with permissions.
You need to post of other libraries.
