### ISSUE TITLE
"decode image error" with Webp images on iOS

### ISSUE THREAD

**Issue by cpboyd** [fluttercandies/flutter_image_editor#42]
I'm using https://github.com/fluttercandies/extended_image/blob/bea01a274fb621ab82db1ae8de4b4dc1c0b8bbac/example/lib/pages/image_editor_demo.dart with a webp image and keep getting `decode image error`.

Webp is supported by Flutter:
https://github.com/flutter/flutter/issues/9857

I'm guessing this is because iOS doesn't natively support Webp, but perhaps there should be some sort of workaround since Flutter has built-in support?

**Comment by CaiJingLong** [comment]
There is currently no solution.

**Comment by cpboyd** [comment]
@CaiJingLong I found a solution: https://github.com/mattt/WebPImageSerialization

The library "swizzles" the ObjC methods of UIImage to add WebP support, automatically falling back to the native method if it's not a WebP image.

**Comment by CaiJingLong** [comment]
Yep, you must first convert the picture to a supported format.
