### ISSUE TITLE
Documentation for EditorText. 

### ISSUE THREAD

**Issue by cimplesid** [fluttercandies/flutter_image_editor#45]
` EditorText(
        offset: const Offset(79.1, 201.8),
        text: _controller.text,
        fontSizePx: size,
        textColor: const Color(0xFF995555),
        fontName: fontName,
      ),`

i tried localPosition as well as the globalPosition in the offset but it seems to place somewhere else. How to preemptively calculate the offset to place text in required position in the image

**Comment by CaiJingLong** [comment]
I don't know what your mean.

**Comment by cimplesid** [comment]
![Screenshot_2020-07-24-10-10-03-151_top kikt flutter_image_editor_example](https://user-images.githubusercontent.com/29953052/88360703-6f0af900-cd96-11ea-926c-50fe515a6ee1.jpg)

What i want is place text in the image by defining the offset by gesture on image ?
to accomplish it i used localposition/globalposition as offset neither of them worked . So ho do i write text in specific offset in image

**Comment by CaiJingLong** [comment]
Hi, the example of this plugin just demonstrates the usage of api.
The layout of flutter has nothing to do with this library, the library only handle data of image.

By the way, the offset of this library requires the pixel offset of the picture. The logical pixel of flutter and the pixel of the picture are usually not 1:1, so you should need to convert.
