### ISSUE TITLE
cropAspectRatio changes after rotate

### ISSUE THREAD

**Issue by akadatsky** [fluttercandies/flutter_image_editor#56]
I want to crop photo with AspectRatio 3/4 and give to user an opportunity to rotate photo. 
But after rotation AspectRatio become 4/3. 
Is there any way to fix it?

**Comment by CaiJingLong** [comment]
This library just edits your pictures according to the parameters you provide.

**Comment by CaiJingLong** [comment]
This library only processes image data, and the UI has nothing to do with this library.
