### ISSUE TITLE
add text to image

### ISSUE THREAD

**Issue by Hopheylalal** [fluttercandies/flutter_image_editor#59]
Why my text add only to left top corner?  i try change offset: Offset(1, 1),but it do not working .

```dart
textOption.addText(
      EditorText(
        text: '$lat $lng',
        fontSizePx: size,
        textColor: const Color(0xFF995555),
        offset: Offset(1, 1),
      ),
    );
    option.outputFormat = const OutputFormat.jpeg(100);

    option.addOption(textOption);
```

**Comment by raksha108** [comment]
Same issue with my app.
Please suggest solution

**Comment by CaiJingLong** [comment]
The value of the offset is pixel.
You can try to modify the value of `offset` to a larger, such as 200x200, or 500x500

**Comment by huylethanh** [comment]
Need to calculate the rate then use it on the option, becasue the image size is different the image display on the screen.

**Comment by liangxianshen** [comment]
How should offset be used? My picture is 1440 * 3200, and I want to put a string of text at the bottom. Why doesn't the dy setting of 3000 work? 1500 is correct.

**Comment by liangxianshen** [comment]
> 偏移量的值是像素。你可以尝试把 的值改大，比如 200x200 或 500x500`offset`

It's not pixels.

**Comment by liangxianshen** [comment]
> 需要计算速率然后用在选项上，因为屏幕上显示的图像大小不同。
> 
> ```
> textOption.addText(
>       EditorText(
>         text: '$lat $lng',
>         fontSizePx: size,
>         textColor: const Color(0xFF995555),
>         offset: Offset(displayWidth* rate, displayHegith*rate),
>       ),
>     );
>     option.outputFormat = const OutputFormat.jpeg(100);
> 
>     option.addOption(textOption);
> ```

This offset is so difficult to understand. The document says it's pixels, but here it's not pixels.
