### ISSUE TITLE
Request Update for Newest Flutter & Dart SDK

### ISSUE THREAD

**Issue by DenisMrGnusa** [fluttercandies/flutter_image_editor#89]
**My flutter & dart version**
Flutter 3.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cd41fdd495 (7 days ago) • 2022-06-08 09:52:13 -0700
Engine • revision f15f824b57
Tools • Dart 2.17.3 • DevTools 2.12.2

**Primary Problem**

When adding _flutter_image_editor_ package to my **pubspec** I've error like bellow:

```
Because image_editor 1.0.2 requires SDK version <2.0.0 and no versions of image_editor match >1.0.2 <2.0.0, image_editor ^1.0.2 is forbidden.
So, because peduli_bencana_presisi depends on image_editor ^1.0.2, version solving failed.
```

**Comment by CaiJingLong** [comment]
https://github.com/fluttercandies/flutter_image_editor/blob/2c2ac43757dd8dca6cab78c72b30195a4eda8b22/pubspec.yaml#L7-L8
The package support Flutter 2.x and 3.x
